Add note about CLI usage on MacOS
azagaya/laigter pull request #84
Opened 2021-04-14 23:16 UTC by cjonasw

2021-04-14 23:30 UTC, Calinou requested changes

2021-04-14 23:30 UTC, Calinou commented on README.md
> +``` laigter --no-gui -d <pathToDiffuseTexture>.png -n ``` etc.
```suggestion
#### MacOS

Symlink the binary. Replace `/Applications` with the path to Laigter.

```
sudo ln -s /Applications/laigter.app/Contents/MacOS/laigter /usr/local/bin
```

Now that the `laigter` binary is symlinked to a location in the `PATH` environment variable,
you can run Laigter from anywhere:

```
laigter --no-gui -d "<pathToDiffuseTexture>.png" --r "<pathToPresetProfile>" -n -c -o -p
```

2021-04-15 11:12 UTC, cjonasw commented
LGTM

2021-04-15 11:26 UTC, merged

2021-04-15 11:26 UTC, azagaya commented
thanks!